on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: temurin
    - uses: coursier/cache-action@v6
    - run: sbt unusedCode "scalafix WarnUnusedCode" "scalafix RemoveUnusedCode"
